update=17.07.2018 15:52:27
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=switches
LibName4=relays
LibName5=motors
LibName6=transistors
LibName7=conn
LibName8=linear
LibName9=regul
LibName10=74xx
LibName11=cmos4000
LibName12=adc-dac
LibName13=memory
LibName14=xilinx
LibName15=microcontrollers
LibName16=dsp
LibName17=microchip
LibName18=analog_switches
LibName19=motorola
LibName20=texas
LibName21=intel
LibName22=audio
LibName23=interface
LibName24=digital-audio
LibName25=philips
LibName26=display
LibName27=cypress
LibName28=siliconi
LibName29=opto
LibName30=atmel
LibName31=contrib
LibName32=valves
LibName33=F:/Daten/OneDrive/Projekte/KiCAD libraries/MeineBibli
LibName34=F:/Daten/OneDrive/Projekte/KiCAD libraries/EigeneModule
LibName35=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName36=C:/Program Files/KiCad/share/kicad/library/74xx
LibName37=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName38=C:/Program Files/KiCad/share/kicad/library/actel
LibName39=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName40=C:/Program Files/KiCad/share/kicad/library/allegro
LibName41=C:/Program Files/KiCad/share/kicad/library/Altera
LibName42=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName43=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName44=C:/Program Files/KiCad/share/kicad/library/atmel
LibName45=C:/Program Files/KiCad/share/kicad/library/audio
LibName46=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName47=C:/Program Files/KiCad/share/kicad/library/bbd
LibName48=C:/Program Files/KiCad/share/kicad/library/bosch
LibName49=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName50=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName51=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName52=C:/Program Files/KiCad/share/kicad/library/conn
LibName53=C:/Program Files/KiCad/share/kicad/library/contrib
LibName54=C:/Program Files/KiCad/share/kicad/library/cypress
LibName55=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName56=C:/Program Files/KiCad/share/kicad/library/device
LibName57=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName58=C:/Program Files/KiCad/share/kicad/library/diode
LibName59=C:/Program Files/KiCad/share/kicad/library/display
LibName60=C:/Program Files/KiCad/share/kicad/library/dsp
LibName61=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName62=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName63=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName64=C:/Program Files/KiCad/share/kicad/library/gennum
LibName65=C:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName66=C:/Program Files/KiCad/share/kicad/library/hc11
LibName67=C:/Program Files/KiCad/share/kicad/library/infineon
LibName68=C:/Program Files/KiCad/share/kicad/library/intel
LibName69=C:/Program Files/KiCad/share/kicad/library/interface
LibName70=C:/Program Files/KiCad/share/kicad/library/intersil
LibName71=C:/Program Files/KiCad/share/kicad/library/ir
LibName72=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName73=C:/Program Files/KiCad/share/kicad/library/leds
LibName74=C:/Program Files/KiCad/share/kicad/library/LEM
LibName75=C:/Program Files/KiCad/share/kicad/library/linear
LibName76=C:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName77=C:/Program Files/KiCad/share/kicad/library/maxim
LibName78=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName79=C:/Program Files/KiCad/share/kicad/library/memory
LibName80=C:/Program Files/KiCad/share/kicad/library/microchip
LibName81=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName82=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName83=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName84=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName85=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName86=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName87=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName88=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName89=C:/Program Files/KiCad/share/kicad/library/modules
LibName90=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName91=C:/Program Files/KiCad/share/kicad/library/motorola
LibName92=C:/Program Files/KiCad/share/kicad/library/motors
LibName93=C:/Program Files/KiCad/share/kicad/library/msp430
LibName94=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName95=C:/Program Files/KiCad/share/kicad/library/nxp
LibName96=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName97=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName98=C:/Program Files/KiCad/share/kicad/library/opto
LibName99=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName100=C:/Program Files/KiCad/share/kicad/library/philips
LibName101=C:/Program Files/KiCad/share/kicad/library/power
LibName102=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName103=C:/Program Files/KiCad/share/kicad/library/powerint
LibName104=C:/Program Files/KiCad/share/kicad/library/pspice
LibName105=C:/Program Files/KiCad/share/kicad/library/references
LibName106=C:/Program Files/KiCad/share/kicad/library/regul
LibName107=C:/Program Files/KiCad/share/kicad/library/relays
LibName108=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName109=C:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName110=C:/Program Files/KiCad/share/kicad/library/sensors
LibName111=C:/Program Files/KiCad/share/kicad/library/silabs
LibName112=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName113=C:/Program Files/KiCad/share/kicad/library/stm8
LibName114=C:/Program Files/KiCad/share/kicad/library/stm32
LibName115=C:/Program Files/KiCad/share/kicad/library/supertex
LibName116=C:/Program Files/KiCad/share/kicad/library/switches
LibName117=C:/Program Files/KiCad/share/kicad/library/texas
LibName118=C:/Program Files/KiCad/share/kicad/library/transf
LibName119=C:/Program Files/KiCad/share/kicad/library/transistors
LibName120=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName121=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName122=C:/Program Files/KiCad/share/kicad/library/valves
LibName123=C:/Program Files/KiCad/share/kicad/library/video
LibName124=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName125=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName126=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName127=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName128=C:/Program Files/KiCad/share/kicad/library/zetex
LibName129=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName130=F:/Daten/OneDrive/Projekte/KiCAD libraries/ESP8266
LibName131=F:/Daten/OneDrive/Projekte/KiCAD libraries/QR_Tasker
